# Generated by Django 4.2.7 on 2023-11-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WriteHomework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riyazi', models.CharField(max_length=100)),
                ('farsi', models.CharField(max_length=100)),
                ('zist', models.CharField(max_length=100)),
                ('fizic', models.CharField(max_length=100)),
                ('hediye', models.CharField(max_length=100)),
                ('amadegi', models.CharField(max_length=100)),
                ('motaleat', models.CharField(max_length=100)),
                ('zaban', models.CharField(max_length=100)),
                ('mokaleme', models.CharField(max_length=100)),
                ('arabi', models.CharField(max_length=100)),
                ('goran', models.CharField(max_length=100)),
                ('negaresh', models.CharField(max_length=100)),
                ('honar', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='MondayModel',
        ),
        migrations.DeleteModel(
            name='TuesdayModel',
        ),
    ]
