# Generated by Django 4.2.7 on 2023-11-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_writehomework_delete_mondaymodel_delete_tuesdaymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='writehomework',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
