# Generated by Django 4.2.7 on 2023-11-08 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_writehomework_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WriteHomework',
        ),
    ]
