# Generated by Django 4.2.7 on 2023-11-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WriteHomework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('math', models.CharField(blank=True, max_length=100)),
                ('literature', models.CharField(blank=True, max_length=100)),
                ('biology', models.CharField(blank=True, max_length=100)),
                ('physics', models.CharField(blank=True, max_length=100)),
                ('religious', models.CharField(blank=True, max_length=100)),
                ('Defense_readiness', models.CharField(blank=True, max_length=100)),
                ('Social_studies', models.CharField(blank=True, max_length=100)),
                ('english', models.CharField(blank=True, max_length=100)),
                ('conversation', models.CharField(blank=True, max_length=100)),
                ('arabic', models.CharField(blank=True, max_length=100)),
                ('quran', models.CharField(blank=True, max_length=100)),
                ('writeing', models.CharField(blank=True, max_length=100)),
                ('art', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
