# Generated by Django 4.2.7 on 2023-11-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='writehomework',
            name='more_description',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
