# Generated by Django 4.2.7 on 2023-12-07 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_writehomework_more_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='writehomework',
            name='grade',
            field=models.CharField(default=datetime.datetime(2023, 12, 7, 12, 35, 15, 887808), max_length=50),
            preserve_default=False,
        ),
    ]
